# Single Node Implementations
### for Deep Learning (MTH4320)

## Gradient Descent

In [72]:
import numpy as np

In [3]:
# create a function that estimates gradients
def estimate_gradient(f, x, h) :
    # assume x is multidimensional
    n = len(x)
    gradient = np.zeros(n)
    
    for i in range(n):
        xUp = x.copy()
        xUp[i] += h
        gradient[i] = (f(xUp) - f(x))/h
        
    return gradient

In [4]:
# f = function, x = list of numbers, h = constant

In [5]:
f = lambda x: x[0]**2

estimate_gradient(f, [5], 0.0000001)

array([10.00000012])

In [6]:
f = lambda x: x[0]**2 + x[1]**2

estimate_gradient(f, [4, 3], 0.0000001)

array([8.00000013, 6.00000007])

In [7]:
def gradient_descent(f, x0, alpha, h, eps, max_iterations):
    x = x0 # initial guess for minimum
    
    for i in range(max_iterations):
        # could also do a while loop on size of the gradient
        
        gradient = estimate_gradient(f, x, h)
        
        #stop if gradient is small
        if np.linalg.norm(gradient) < eps:
            print('iterations: ')
            print(i)
            return x
        
        # stop if we reach max iterations
        elif i == max_iterations - 1:
            print('Did not converge')
            return x
        # weight update
        x -= alpha*gradient

In [18]:
# x can me multivariate, if stored as a list
f = lambda x: x[0]**2 + x[1]**2

gradient_descent(f, [5, -2], 0.1, 0.0000001, 0.00000001, 1000000)

iterations: 
94


array([-4.61146622e-08, -5.15541351e-08])

## Least Squares Gradient

In [79]:
class LeastSquaresGradient:
    def fit(self, X, y, w0, alpha, h, eps, max_iterations):
        
        self.n = X.shape[0]
        self.d = X.shape[1]
        self.h = h
        self.alpha = alpha
        self.initialGuess = w0
        
        self.data = np.hstack((np.ones([self.n, 1]), X))
        self.outputs = y
        
        X = self.data
        
        L = lambda w: ((X @ w).T - y.T) @ (X @ w - y)
        
        # 'self.w' allows other functions in class to access this variable
        self.w = self.gradient_descent(L, self.initialGuess, self.alpha, self.h, eps, max_iterations)
        
    def predict(self, X):
        
        yPredicted = np.empty([X.shape[0],1])
            
        X = np.hstack((np.ones([X.shape[0],1]), X))
        for row in range(X.shape[0]):
            yPredicted[row] = self.w @ X[row,]
            
        return yPredicted
        # returns predicted output
        
    def gradient_descent(self, f, x0, alpha, h, eps, max_iterations):
        x = x0 # initial guess for minimum

        for i in range(max_iterations):
            # could also do a while loop on size of the gradient

            gradient = estimate_gradient(f, x, h)

            #stop if gradient is small
            if np.linalg.norm(gradient) < eps:
                print('iterations: ')
                print(i)
                return x

            # stop if we reach max iterations
            elif i == max_iterations - 1:
                print('Did not converge')
                return x
            # weight update
            x -= alpha*gradient
  

In [87]:
X = np.array([[6], [7], [8], [9], [7]])
y = np.array([1, 2, 3, 3, 4])

# instantiate a model from the class
model = LeastSquaresGradient()

# fit the mdoel
model.fit(X, y, [0, 0], alpha = 0.001, h = 0.001, eps = 0.001, max_iterations = 100000)

predictions = model.predict(X)
print('\nThe predicted y values are', predictions.T[0])

print('The real y values are', y)


iterations: 
29751

The predicted y values are [1.87933494 2.39380935 2.90828376 3.42275817 2.39380935]
The real y values are [1 2 3 3 4]


In [99]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [100]:
df=pd.read_csv('US_State_Data.csv').to_numpy()

# need to standardize the colums of data x = (x-mean)/st. dev
X = np.array(df[:,1:8], dtype = float)
X = (X - np.mean(X, axis = 0)) / np.std(X, axis = 0)

y = np.array(df[:,8], dtype = float)

trainX, testX, trainY, testY = train_test_split(X, y, test_size = 0.25, random_state = 1)

model = LeastSquaresGradient()

model.fit(trainX, trainY, [0,0,0,0,0,0,0,0], alpha = 0.001, h = 0.001, eps = 0.001, max_iterations = 100000)

trainPredictions = model.predict(trainX)
print('\nThe r^2 score is', r2_score(trainY, trainPredictions))

iterations: 
1202

The r^2 score is 0.40352475701082924
